/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ===== GALLIFREY BRAND COLORS =====
        "gallifrey-white": "hsl(var(--gallifrey-white))",
        "gallifrey-off-white": "hsl(var(--gallifrey-off-white))",
        "gallifrey-light-gray": "hsl(var(--gallifrey-light-gray))",
        "gallifrey-medium-gray": "hsl(var(--gallifrey-medium-gray))",
        "gallifrey-dark-gray": "hsl(var(--gallifrey-dark-gray))",
        "gallifrey-charcoal": "hsl(var(--gallifrey-charcoal))",
        "gallifrey-teal": "hsl(var(--gallifrey-teal))",
        "gallifrey-teal-dark": "hsl(var(--gallifrey-teal-dark))",
        "gallifrey-border": "hsl(var(--gallifrey-border))",

        // ===== OWN YOUR NARRATIVE CAMPAIGN COLORS =====
        "oyn-stone": {
          50: "hsl(var(--oyn-stone-50))",
          100: "hsl(var(--oyn-stone-100))",
          200: "hsl(var(--oyn-stone-200))",
          300: "hsl(var(--oyn-stone-300))",
          400: "hsl(var(--oyn-stone-400))",
          500: "hsl(var(--oyn-stone-500))",
          600: "hsl(var(--oyn-stone-600))",
          700: "hsl(var(--oyn-stone-700))",
          800: "hsl(var(--oyn-stone-800))",
          900: "hsl(var(--oyn-stone-900))",
        },
        "oyn-orange": {
          50: "hsl(var(--oyn-orange-50))",
          100: "hsl(var(--oyn-orange-100))",
          200: "hsl(var(--oyn-orange-200))",
          300: "hsl(var(--oyn-orange-300))",
          400: "hsl(var(--oyn-orange-400))",
          500: "hsl(var(--oyn-orange-500))",
          600: "hsl(var(--oyn-orange-600))",
          700: "hsl(var(--oyn-orange-700))",
          800: "hsl(var(--oyn-orange-800))",
          900: "hsl(var(--oyn-orange-900))",
        },

        // ===== SEMANTIC COLOR MAPPINGS =====
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },

        // ===== LEGACY COLORS (for backward compatibility) =====
        "pure-white": "hsl(var(--gallifrey-white))",
        "off-white": "hsl(var(--gallifrey-off-white))",
        "light-gray": "hsl(var(--gallifrey-light-gray))",
        "medium-gray": "hsl(var(--gallifrey-medium-gray))",
        "dark-gray": "hsl(var(--gallifrey-dark-gray))",
        charcoal: "hsl(var(--gallifrey-charcoal))",
        "teal-accent": "hsl(var(--gallifrey-teal))",
        "teal-dark": "hsl(var(--gallifrey-teal-dark))",
      },
      fontFamily: {
        heading: ["Montserrat", "sans-serif"],
        body: ["Source Sans Pro", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        logo: ["Playfair Display", "serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};
